/**
 * Test script for CashNDrive API with GPT-4o integration
 */

const config = require('./config');

async function testAPI() {
  console.log('\n🧪 Testing CashNDrive API with GPT-4o\n');
  console.log('═══════════════════════════════════════\n');

  const API_BASE = 'http://localhost:7071/api';

  // Test 1: Health Check
  console.log('1️⃣  Testing Health Check...');
  try {
    const response = await fetch(`${API_BASE}/health`);
    const data = await response.json();
    console.log('   ✅ Health:', data.status);
  } catch (error) {
    console.log('   ❌ Health check failed:', error.message);
  }
  console.log('');

  // Test 2: AI Response (Simple greeting)
  console.log('2️⃣  Testing AI Response - Greeting...');
  try {
    const response = await fetch(`${API_BASE}/GetAIResponse`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userMessage: 'Dobrý den, chtěl bych informace o vašich službách.'
      })
    });
    const data = await response.json();
    console.log('   User: Dobrý den, chtěl bych informace o vašich službách.');
    console.log('   AI: ' + data.response);
    console.log('   ✅ Response received');
  } catch (error) {
    console.log('   ❌ AI Response failed:', error.message);
  }
  console.log('');

  // Test 3: AI Response with conversation history
  console.log('3️⃣  Testing AI Response - With History...');
  try {
    const response = await fetch(`${API_BASE}/GetAIResponse`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userMessage: 'Jaké jsou ceny?',
        conversationHistory: [
          { type: 'user', text: 'Dobrý den' },
          { type: 'ai', text: 'Dobrý den, jsem AI asistent CashNDrive.' },
          { type: 'user', text: 'Zajímá mě vaše služba' },
          { type: 'ai', text: 'Rádi vám poskytneme informace o našich AI hlasových službách.' }
        ]
      })
    });
    const data = await response.json();
    console.log('   User: Jaké jsou ceny?');
    console.log('   AI: ' + data.response);
    console.log('   ✅ Context-aware response received');
  } catch (error) {
    console.log('   ❌ Context test failed:', error.message);
  }
  console.log('');

  // Test 4: Generate Summary
  console.log('4️⃣  Testing Summary Generation...');
  try {
    const response = await fetch(`${API_BASE}/GenerateSummary`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        messages: [
          { type: 'user', text: 'Dobrý den, potřebuji pomoc s nastavením AI asistenta.' },
          { type: 'ai', text: 'Dobrý den! Rád vám pomohu. Co konkrétně potřebujete nastavit?' },
          { type: 'user', text: 'Chci, aby asistent uměl mluvit česky a odpovídat na dotazy o cenách.' },
          { type: 'ai', text: 'Rozumím. Náš systém podporuje češtinu nativně a můžeme nastavit automatické odpovědi na cenové dotazy.' },
          { type: 'user', text: 'Kolik to bude stát?' },
          { type: 'ai', text: 'Základní balíček začíná na 5000 Kč měsíčně. Zahrnuje 1000 minut hovorů a podporu 24/7.' },
          { type: 'user', text: 'To zní dobře. Můžete mi poslat nabídku na email?' },
          { type: 'ai', text: 'Samozřejmě! Na jaký email vám mám nabídku zaslat?' }
        ],
        duration: 180
      })
    });
    const data = await response.json();
    console.log('   Summary generated:');
    console.log('   - Reason:', data.reason);
    console.log('   - Sentiment:', data.sentiment);
    console.log('   - Follow-up:', data.followUp);
    console.log('   - Generated by:', data.generatedBy || 'Rule-based');
    if (data.keyPoints) {
      console.log('   - Key Points:');
      data.keyPoints.forEach(point => console.log('     •', point));
    }
    console.log('   ✅ Summary generated successfully');
  } catch (error) {
    console.log('   ❌ Summary generation failed:', error.message);
  }
  console.log('');

  // Configuration summary
  console.log('═══════════════════════════════════════');
  console.log('📋 Configuration Status:');
  console.log('   Endpoint:', config.AZURE_AI_ENDPOINT || '❌ Not set');
  console.log('   API Key:', config.AZURE_AI_KEY ? '✅ Configured' : '❌ Not set');
  console.log('   Deployment:', config.AZURE_AI_DEPLOYMENT_NAME || '❌ Not set');
  console.log('   Speech Region:', config.AZURE_SPEECH_REGION || '❌ Not set');
  console.log('');
  console.log('🎉 API Testing Complete!\n');
}

// Run tests
testAPI().catch(console.error);
